language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
- pypy3
install:
- pip install -Ur requirements.txt
script:
- py.test . -v --cov . --cov-report term-missing
after_success:
- coveralls
deploy:
  provider: pypi
  user: linuxdaemon
  password:
    secure: XEJ3/PkEEky52gANfuGbPV+aN0Yg8rYHa/SJWd24EWfxlEwjhIzQQbQUhjc4xSSiFyOHd2Hqgs9ajX9UOVSN0HrAtogZSAqrfm0N9vNSGknLluYbJPFUVhLjt3wZPtU5+HLdZ+tJo1ZAHq2NTTJ2E2hFP3m4e3isN6fj2Q8NWPdC4U8shayQDLsAB72oP00Ocy3I2slMw5bEPmIl8KK/0vB3xkV6hbAC7GjbTeWqB73IFe+DEbZR6voezyfThAM8SGBCCz5L0dkd1IUkdxS6nEOQg+CiF8eGF/YbipIwaB5KE5Vg2BcGFyk/9GH5+4hNKJSspweqeqb6ltnj7aLDX3MOeCkgQqsKf2HyQfYkBmsHd0TDDgJEixNrh8LAT+OmsTbmn6vany+aN8f/7IIGAQHct8dFedCJEuC70wX5adbTMuz0MmtgvdLjWoofCPAR2HxLkU2Q0Y1oRaifoC4G3YJHvT7QJ6ENm/RV/2FkmDR004FKU5M+/3TL+W8QMCIWnu+l5byo4odmuvZuk3WtYhuNJiEwRAhjoOCSWb0MpqAWl/69drH3m8RAfk3ERSsYgyjTcTuggL3LY17B1ubpqyFSDgL2c27xoBdfCtof69lZ7f1grbFQqNpZL/byJ7nb+qCOBv0L9PAghMrBnXLcX2UaJjbQB4OvNBQfCqWpU0M=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: TotallyNotRobots/py-irclib
    python: '3.6'
env:
- PYTHONPATH=.
