language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - "pip install -Ur requirements.txt"

script:
  - "py.test . -v --cov . --cov-report term-missing"

after_success:
  - "coveralls"

env:
  - PYTHONPATH=.
